### ISSUE TITLE
VS. Whitty is not accurate.

### ISSUE THREAD

**Issue by foxsouns** [hdboye/FnfModAttempt#3]
**Mod name**
VS. Whitty

**Describe the bug**
WASD is not remapped as DFJK, cut-scenes are not present, and it is not its own week.

**To Reproduce**
1. Play the VS. Whitty mod
2. View the differences.

**Expected behavior**
There should be a separate week for Whitty, remapped WASD controls, and Whitty should have the cutscenes with his week. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Chrome OS 86.0.4240.199
 - Browser: Chrome
 - Version: 86.0.4240.199

**Additional context**
This might be out of the realm of possibility, considering it's a custom exe mod. Still, I hope to at least know what's prohibiting it if it cannot be implimented.

**Comment by foxsouns** [comment]
oh, i forgot: gf's changing in Whitty as well

**Comment by hdboye** [comment]
We have 3 options with the whitty mod.
1. Recreate the entire mod from scratch with only the assets available (which would take a long time and would eventually not work out probably)
2. Only add the songs
3. Wait for the source code to be public (which it will probably never be since kadedev really likes to have his mods closed-sourced)

We're not going with option 1, because it would probably not work considering the lack of haxe coding skills i have.
Option 3 would entirely depend on KadeDev.

The only current option we have is option 2, which we have used. If the source code for whitty ever goes public, then we will update the mod to have everything seen in the original mod.

**Comment by foxsouns** [comment]
Let's hope that the source eventually gets out.

**Comment by foxsouns** [comment]
Wait, @hdboye: we could still change the controls pretty trivially. I've made the PR at #4
